require("indent_blankline").setup({
  space_char_blankline = " ",
  show_current_context = true,
  show_current_context_start = true,
  use_treesitter = true,
  context_highlight_list = {
    "RainbowRed",
    "RainbowYellow",
    "RainbowBlue",
    "RainbowOrange",
    "RainbowGreen",
    "RainbowViolet",
    "RainbowCyan",
  },
  filetype_exculde = {
    "alpha",
    "packer",
    "NvimTree",
    "lsp-install",
    "help",
    "TelescopePrompt",
    "TelescopeResults",
  },
  buftype_exclude = { "terminal", "nofile" },
})
